spring.application.name=Learnex

spring.datasource.url=jdbc:postgresql://localhost:6767/LearnexDev
spring.datasource.username=postgres
spring.datasource.password=MTKgtgaming
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=1008
server.servlet.context-path=/learnex

jwt.secret=RNXV2a1SeT82URyDWw3uBpZWL4ivCCdThShwi0vuqJk=
jwt.expiration=3600000

